name: Execute test suite
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm test
